name: Cypress testing
on: push
jobs:
  build-and-run-tests:
    runs-on: ubuntu-16.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: forge
          MYSQL_DATABASE: forge
          DB_HOST: 127.0.0.1
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Copy ENV Laravel Configuration for CI
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      working-directory: ./thesisproject

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Dependencies (PHP vendors)
      working-directory: ./thesisproject
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist && npm ci

    - name: Generate key
      working-directory: ./thesisproject
      run: php artisan key:generate

    - name: Build site
      working-directory: ./thesisproject
      run: npm run dev

    - name: Migrate MySQL DB
      working-directory: ./thesisproject
      env: 
        DB_CONNECTION: mysql
        DB_DATABASE: forge
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: forge
      run: php artisan migrate:fresh --seed

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        install: false
        start: npm start
        wait-on: http://localhost:8000
        working-directory: ./thesisproject
